softeerbootcamp/be-java-lotto

- .idea/misc.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/LottoNumber.java
- src/main/java/kr/codesquad/Main.java
> 1주차 로또 step1

- .idea/misc.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/Main.java
main 함수에 풀이 한 후 class의 필요성을 느껴서 lotto class를 새로 생성 한 후 리팩토링 진행중입니다.
> 로또1단계풀이 후 리팩토링 진행중

- .idea/misc.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/LottoStat.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/UserInputHandler.java
- src/main/java/kr/codesquad/Utility.java
> 2022.01.02

- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/controller/LottoController.java
- src/main/java/kr/codesquad/model/Lotto.java
- src/main/java/kr/codesquad/model/User.java
- src/main/java/kr/codesquad/model/WinningLotto.java
- src/main/java/kr/codesquad/util/CommonMessage.java
- src/main/java/kr/codesquad/view/PrintView.java
- src/main/java/kr/codesquad/view/ReceiveView.java
- src/test/java/kr/codesquad/model/LottoTest.java
- src/test/java/kr/codesquad/model/UserTest.java
당첨번호 입력받는 곳까지 구현하였습니다.
(당첨통계 기능부분은 아직 구현하지 못하였습니다.)
> PR: Step1 제출합니다.

- .idea/gradle.xml
- .idea/misc.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/Main.java
브랜치명이 잘못되어 있어 재제출드립니다.
* shuffle을 통해 로또 생성 구현
* 사용자 입력 구현
* depth1을 만족하도록 비교 구현
* 통계 결과 출력 구현
> [신정아] 로또 1단계 기본 기능 구현 재제출합니다.

- .idea/workspace.xml
- src/main/java/kr/codesquad/Main.java
> [로또 step1] - 당첨 통계 메소드 구현

- .idea/gradle.xml
- .idea/misc.xml
- .idea/vcs.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/Main.java
로또 구입 금액을 입력하면 구입 금액에 해당하는 로또를 발급해야 한다.
로또 1장의 가격은 1000원이다.
당첨 번호를 입력받아서 수익률을 출력한다.
메소드의 indent(인덴트, 들여쓰기) depth를 1단계로 구현한다.
메소드의 크기가 최대 10라인을 넘지 않도록 구현한다.
ArrayList를 사용해서 구현한다.
> feat: 기본 구현 추가

- .idea/workspace.xml
- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/WinNum.java
당첨 통계 계산 기능 추가, 구매한 로또 번호 출력 수정,  ArrayList<Integer>에서 List<Integer>로 수정 후 재 제출합니다.
> [로또 1단계] 기능 추가 및 수정

- src/main/java/kr/codesquad/Main.java
- 로또 번호 자동 생성 기능의 함수 구현
- 메인 함수에서 구현했던 구입 금액 입력 받는 기능을 가독성을 위해 따로 함수로 추출
- 당첨 번호 입력하는 함수 구현
- 당첨 번호가 몇 개인지 체크하는 함수 구현
- 현재 Main에서 코드를 모두 구현한 상태여서 객체 따로 나눠서 구현할 예정
> 1주차 로또 1단계 - 기본 기능 구현 1일차

- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/LottoSystem.java
- src/main/java/kr/codesquad/Main.java
- 기존에 Main에 모두 구현되어 있던 코드를 LottoSystem과 Lotto 객체로 나누어 구현
- LottoSystem: Lotto를 구입하고 당첨 결과를 출력하는 기능을 담당하는 객체
- Lotto: 발급받은 Lotto 정보를 가지고 있는 객체
- 로또 당첨 결과를 출력하는 기능의 함수 구현
> 1주차 로또 1단계 - 기본 기능 구현 완료

- .gitignore
- src/main/java/kr/codesquad/controller/LottoController.java
- src/main/java/kr/codesquad/model/Lotto.java
- src/main/java/kr/codesquad/model/Result.java
- src/main/java/kr/codesquad/model/User.java
- src/main/java/kr/codesquad/model/WinningLotto.java
- src/main/java/kr/codesquad/model/WinningStatic.java
- src/main/java/kr/codesquad/util/CommonMessage.java
- src/main/java/kr/codesquad/view/PrintView.java
- src/main/java/kr/codesquad/view/ReceiveView.java
- src/test/java/kr/codesquad/model/ResultTest.java
- src/test/java/kr/codesquad/model/UserTest.java
- src/test/java/kr/codesquad/model/WinningStaticTest.java
- Step1에 구현하지못한 기능
-  당첨통계 계산 기능
- 당첨통계 출력
- 수익률 계산 및 출력
- enum을 활용한 당첨 통계 관리
- 3개일치부터 6개일치까지의 값을 enum하여 관리
- 보너스볼
- 보너스볼 입력받기 기능 추가
- 보너스볼을 고려한 2등 계산 추가
- 보너스볼을 고려한 당첨통계 출력값 수정
그룹내 코드리뷰후 피드백 반영
- Stream을 사용한 코드 간소화
- 상수위치 각 객체 특성에 맞게 위치 변경
- 당첨결과를 당첨번호와 보너스번호를 가진 객체로 리팩터링
> [김규민] 로또2단계-Step2

- .idea/workspace.xml
- src/main/java/kr/codesquad/LottoMachine.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/User.java
* 기존 1단계 구현에 보너스 번호를 추가
* enum 및 enum map을 활용하여 등수에 따른 매치 개수와 상금 액수 관리
* user 클래스와 lotto 클래스를 분리하여 사용자 인풋에 따른 입력값과 자동 생성 로또 따로 관리
* 기존의 lotto 클래스를 통해서는 당첨 비교를 구현
> 로또2단계 - 보너스 번호 추가

- .gitignore
- .idea/workspace.xml
- src/main/java/kr/codesquad/LottoController.java
- src/main/java/kr/codesquad/LottoService.java
- src/main/java/kr/codesquad/LottoView.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/Rank.java
- src/main/java/kr/codesquad/Row.java
- src/main/java/kr/codesquad/Statistic.java
Enum을 활용하여 로또 값 리스트를 refactor하였으며, 보너스 숫자를 입력받아 이에 맞게 출력될 수 있도록 구현하였습니다.
그 과정에서 코드의 복잡도가 계속 증가하고, 유지 보수 면에서 한계를 느껴 개선방안을 찾고자 토의를 거쳐
Controller와 Service 레벨을 나누어 계층적으로 로직을 처리할 수 있도록 구조를 개선하였습니다.
추후 View기능을 따로 빼는 것이 더 좋을 것 같다는 판단에 Console에 입,출력만을 담당하는 View를 최상단에 두는 방식으로 수정하였습니다. 
그러나 Enum을 구분하고 처리하는 과정에서 depth1을 유지하기 위해 Service단에서 Rank 자체가 아닌 Rank의 상금에 의존하여 분류한 부분이 있어, 상금 기준이 unique하다면 문제가 되지 않지만 중복되는 상금이 존재하게 될 시 오류가 발생할 수 있다는 위협이 존재하여 더 나은 방안에 대해 연구가 필요할 것 같습니다.
> Step2 구현 및 프로그램의 전체적인 구조 변경

- .idea/uiDesigner.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/LottoNumber.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/controller/LottoController.java
- src/main/java/kr/codesquad/domain/Lotto.java
- src/main/java/kr/codesquad/domain/Lottos.java
- src/main/java/kr/codesquad/domain/WinLotto.java
- src/main/java/kr/codesquad/view/InputView.java
- src/main/java/kr/codesquad/view/OutputView.java
- 코드 리뷰 후 코드가 객체지향적이지 않다고 느껴 전반적으로 코드 수정
- 최대한 클래스를 분리해보려고 노력함
- 로또 숫자의 최소, 최댓값, 로또 사이즈 (6개) 를 피드백을 반영하여 상수화
> [Step1] - 코드 리팩토링, 전체적인 구조 변경

- .idea/workspace.xml
- src/main/java/kr/codesquad/controller/LottoController.java
- src/main/java/kr/codesquad/domain/Lotto.java
- src/main/java/kr/codesquad/domain/Lottos.java
- src/main/java/kr/codesquad/domain/Rank.java
- src/main/java/kr/codesquad/domain/Result.java
- src/main/java/kr/codesquad/domain/WinLotto.java
- src/main/java/kr/codesquad/view/InputView.java
- src/main/java/kr/codesquad/view/OutputView.java
기능 추가
- WinLotto Class에 bonusBall 추가
- Enum Class 랭크 구현
리팩토링
- Result Class 추가 (당첨 통계 관련)
- Enum 사용으로 인한 당첨통계 출력 메서드 변경
- 당첨로또와 몇 개 일치하는지 확인하는 메서드 변경
> [로또 - Step2] 기능 구현

- src/main/java/kr/codesquad/Application.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/io/Console.java
- src/main/java/kr/codesquad/lotto/LottoAutoFactory.java
- src/main/java/kr/codesquad/lotto/LottoManualFactory.java
- src/main/java/kr/codesquad/lotto/LottoPurchase.java
- src/main/java/kr/codesquad/lotto/LottoService.java
- src/main/java/kr/codesquad/lotto/RandomNumFactory.java
- src/main/java/kr/codesquad/winLotto/WinCount.java
- src/main/java/kr/codesquad/winLotto/WinResult.java
Lotto 관련 기능을 모두 관리하던 LottoService의 책임을 나누기 위해 리팩토링 진행
LottoPurchase : 로또 구매 
LottoAutoFactory : 자동 로또 번호 생성
RandomNumFactory : 랜덤 번호 생성
WinResult : 당첨 결과 계산
생성 후 LottoService 내부 메소드 이동
> [김태완-로또 3단계] 기능 구현에 앞선 리팩토링

- src/main/java/kr/codesquad/LottoChecker.java
- src/main/java/kr/codesquad/LottoMachine.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/Rank.java
- src/main/java/kr/codesquad/UserInput.java
1. 객체가 가져야 할 적절한 상태와 행동이 무엇인지 고민해가며 코드 리팩토링
- Lotto 객체가 로또 하나의 가격 정보를 가지고 있어야 한다고 판단하여 LottoMachine에서 구입 금액 정보를 저장하던 멤버 변수를 없애고 Lotto 객체에 로또 하나의 가격 정보를 담고 있는 멤버 변수 생성
- 로또 당첨 확인을 담당하는 LottoChecker가 당첨 번호와 보너스 번호를 멤버 변수로 가지고 있어야 한다고 판단하여 생성
2. 하드 코딩 돼 있던 부분을 수정하기 위해 당첨 결과 저장하는 자료 구조를 ArrayList가 아닌 EnumMap으로 대체
- 동작이 제대로 이루어지지 않아 수정 중...
> [박준수] 1주차 로또 3단계 - 수동구매 기능 추가 구현 전 코드 리팩토링 중

- .idea/workspace.xml
- src/main/java/kr/codesquad/App.java
- src/main/java/kr/codesquad/Console.java
- src/main/java/kr/codesquad/LottoService/Lotto.java
- src/main/java/kr/codesquad/LottoService/LottoFactory/LottoFactory.java
- src/main/java/kr/codesquad/LottoService/LottoNumber.java
- src/main/java/kr/codesquad/LottoService/LottoResult.java
- src/main/java/kr/codesquad/LottoService/LottoStore.java
- src/main/java/kr/codesquad/LottoService/WinningLotto.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/Rank.java
- src/main/java/kr/codesquad/User.java
- src/main/java/kr/codesquad/View/Console.java
- src/main/java/kr/codesquad/View/IOManager.java
- src/main/java/kr/codesquad/View/IOManagerImpl.java
- Integer 대신에 LottoNumber 이용
- Lotto와 LottoNumber에 정적 팩토리 메서드 추가
- console 대신 Lotto와 LottoNumber 생성자에서 Exception 발생
- 보너스 넘버를 포함한 WinningLotto 클래스 구현
- 리팩토링 진행중
> 1주차 로또 3단계

- .idea/uiDesigner.xml
- .idea/workspace.xml
- src/main/java/kr/codesquad/App.java
- src/main/java/kr/codesquad/IO/Console.java
- src/main/java/kr/codesquad/Lotto/LottoMachine.java
- src/main/java/kr/codesquad/Lotto/LottoStatus.java
- src/main/java/kr/codesquad/LottoMachine.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/User.java
- src/main/java/kr/codesquad/customException/InvalidCashExeption.java
문제 요구사항에 따라 수동 로또 기능을 추가하였습니다.
관련 있는 클래스끼리 패키징하였습니다.
가독성 향상을 위해 Main class의 기능을 제한하고, Console클래스와 App클래스에 그 기능을 나눴습니다.
구매금액 입력 부분에서의 예외처리를 구현하였습니다. 개발자가 의도하지 않은 입력을 넣어도 경고 출력 후 해당 부분부터 다시 실행됩니다.
ex) 숫자가 아닌 입력, int의 최대 범위를 초과한 입력, 자연수가 아닌 입력, 1000단위로 나누어 떨어지지 않는 입력
> [한상훈] Step3 수동 로또 기능 추가 및 예외처리 일부 구현

- .idea/workspace.xml
- src/main/java/kr/codesquad/AutoLottoGenerator.java
- src/main/java/kr/codesquad/LottoController.java
- src/main/java/kr/codesquad/LottoGenerator.java
- src/main/java/kr/codesquad/LottoViewer.java
- src/main/java/kr/codesquad/ManualLottoGenerator.java
- src/main/java/kr/codesquad/domain/Lotto.java
- src/main/java/kr/codesquad/domain/LottoNumber.java
- src/main/java/kr/codesquad/domain/Money.java
- src/main/java/kr/codesquad/domain/Row.java
- src/main/java/kr/codesquad/domain/Statistic.java
- src/main/java/kr/codesquad/domain/WinningNumbers.java
- src/main/java/kr/codesquad/exception/ColumnNotValidException.java
- src/main/java/kr/codesquad/exception/ColumnOverflowException.java
- src/main/java/kr/codesquad/exception/DuplicateLottoNumberException.java
- src/main/java/kr/codesquad/exception/LottoException.java
- src/main/java/kr/codesquad/exception/ManualLottoCntException.java
- src/main/java/kr/codesquad/exception/MoneyNotValidException.java
- src/main/java/kr/codesquad/exception/NumberNotValidException.java
- src/main/java/kr/codesquad/exception/WinningNumbersException.java
Step3의 수동로또 발급 기능 및 예외 처리를 구현하였습니다. 수동로또 생성기 (ManualLottoGenerator) 는 한 줄 (Row)의 로또를 발급하며, 그 과정에서 발생할 수 있는 예외를 Row 도메인 내에 정의된 validation함수를 callback하는 방식으로 처리합니다.
구현한 예외는 아래와 같으며, 모든 예외는 RuntimeException을 상속받은 LottoException 추상 클래스를 상속받고 있습니다.
- ColumnOverflowException : 로또 한 줄에 6개가 아닌 경우 (6개 미만도 포함하기 때문에 작명을 수정해야할 것 같습니다...)
- DuplicateLottoNumberException : 입력받은 한 줄의 로또 숫자가 서로 중복되는 경우
- ManualLottoCntException : 수동으로 구매하는 로또 갯수가  0 ~ (총 갯수) 범위 내에 있지 않은 경우
- MoneyNotValidException : 금액이 최소 1000원 이상, 1000원 단위 입력이 아닌 경우
- NumberNotValidException : 입력된 로또 숫자가 1 ~ 45 를 벗어나는 경우
- WinningNumbersException : 당첨 번호와 보너스 숫자가 겹치는 경우
Exception을 코드가 지저분해지지 않으면서도 적절한 위치에서 발생할 수 있도록 구현하는 것을 목표로 하였습니다. 로또 간의 exception은 Row 도메인 내의 로또 생성 함수에서 validation 처리를 하고, 개별적인 로또 숫자의 경우에는 별도의 LottoNumber 클래스를 만드는 것이 …
> [박승민] Step3 구현

- .idea/workspace.xml
- src/main/java/kr/codesquad/Controller/LottoController.java
- src/main/java/kr/codesquad/View/Input.java
- src/test/java/LottoGameTest.java
놓쳤던 예외처리 추가 
- 수동 로또 개수 입력시 구매 가능한 로또 개수를 넘지 못하게 예외처리
Unit Test 추가
- LottoGame.match() 테스트 추가 ( 학습 자료 참고 )
> [최주형] 5일차 - 로또 3단계 마무리

- src/main/java/kr/codesquad/LottoController.java
- src/main/java/kr/codesquad/LottoViewer.java
- src/main/java/kr/codesquad/ManualLottoGenerator.java
- src/main/java/kr/codesquad/domain/LottoNumber.java
- src/main/java/kr/codesquad/domain/Rank.java
- src/main/java/kr/codesquad/domain/Row.java
- src/main/java/kr/codesquad/domain/Statistic.java
- src/main/java/kr/codesquad/domain/WinningNumbers.java
전체적인 로또 프로그램 기능을 개선하고자 불필요하게 발생하는 메서드를 일관된 로직으로 처리할 수 있도록 개선하였습니다. 주요 대상은
1. 로또 번호 입력 시 : [String input] -> [Integer] -> [LottoNumber] -> [Row]  로의 과정에서 primitive type 자체가 그대로 외부에 노출되지 않고 도메인 레벨에서 convert될 수 있도록 그렇지 않은 코드를 수정하였습니다. 또한 한번 변환된 객체가 다시 Integer나 String 값을 필요로 하는 일이 없도록 구현하였습니다.
2. 통계 출력은 앞으로 Rank 수나 값이 언제든 변화할 수 있다는 점에서 MISS Rank를 그대로 놔두고 출력에서 조건적으로 출력하되 조건문이 계속 발생되지는 않게 구현하였습니다.
1. 한 예로 , LottoNumber간 비교가 필요한 경우에는 Comparable을 구현하여 숫자를 직접 Integer로 비교하지 않아도 되도록 개선하였습니다.
2.  Stream filter를 이용하여 출력할 수 있도록 수정하였습니다. 이를 통해 앞으로 Rank가 수정, 변경, 확장되더라도 필터 조건만 수정해주면 전체 Rank 정보를 모두 테이블에 가지면서도 원하는 Rank만 출력될 수 있게 개선하였습니다.
> [박승민] 로또 프로그램 코드 refactoring

- src/main/java/kr/codesquad/Application.java
- src/main/java/kr/codesquad/domain/lotto/Lotto.java
- src/main/java/kr/codesquad/domain/lotto/LottoService.java
- src/main/java/kr/codesquad/domain/lotto/factory/LottoManualFactory.java
- src/main/java/kr/codesquad/domain/other/Amount.java
- src/main/java/kr/codesquad/domain/other/Bonus.java
- src/main/java/kr/codesquad/domain/other/Money.java
- src/main/java/kr/codesquad/domain/winLotto/WinLotto.java
- src/main/java/kr/codesquad/io/Console.java
기능 구현
- 금액 입력시 예외처리 : 1000원 이하 입력시
- 로또 번호 입력시 예외처리 : 6개 이하로 입력시, 번호를 중복해서 입력시, 로또 번호 범위를 벗어나서 입력시 
- 수동 구매 갯수 입력시 예외처리 : 총 구매할 수 있는 로또 갯수 이상 입력했을 시
- 보너스 번호 입력시 예외처리 : 로또 번호 범위를 벗어나서 입력시
- 형태에 맞지 않게 입력했을 시 예외처리(Integer.parseInt 사용)
리팩토링
- 개수를 저장해주는 Amount 클래스 생성
- 수동로또 개수, 자동로또 개수 Amount 클래스로 변경
- WinLotto 클래스 내부 numberList에서 Lotto 객체로 변경, 관련 부분 수정
-
> [김태완-로또 3단계] 예외처리 구현

- .idea/uiDesigner.xml
- src/main/java/kr/codesquad/Lotto.java
- src/main/java/kr/codesquad/Main.java
- src/main/java/kr/codesquad/Util.java
- src/main/java/kr/codesquad/lotto/AutoLotto.java
- src/main/java/kr/codesquad/lotto/Lotto.java
- src/main/java/kr/codesquad/lotto/ManualLotto.java
- src/main/java/kr/codesquad/lottoSystem/LottoChecker.java
- src/main/java/kr/codesquad/lottoSystem/LottoMachine.java
- src/main/java/kr/codesquad/lottoSystem/Rank.java
필요한 부분 주석 추가 완료
Directory 구조화
수동으로 로또를 구매하거나 당첨 번호를 입력하는 경우 예외 처리 완료
> [박준수] 1주차 로또 3단계 - 수동구매 기능 추가 구현(예외 처리)
